media:
  input: public/images/seminars
  output: /images/seminars

collections:
  - name: seminars
    label: ゼミ紹介
    type: folder
    path: content/seminars
    extension: md
    format: frontmatter
    slug: "{{title}}"
    fields:
      - { name: title, label: ゼミ名, type: string, required: true }
      - { name: teacher, label: 担当教員名, type: string, required: true }
      - { name: image, label: ゼミ画像, type: image }
      - { name: description, label: 一言概要, type: string }
      - { name: body, label: 詳細内容, type: rich-text }
