media:
  input: public/images/seminars
  output: /images/seminars

content:
  - name: seminars
    label: ゼミ紹介
    type: collection
    path: content/seminars
    format: yaml-frontmatter    # ← markdown等の形式を指定
    filename: "{slug}.md"       # ← extension/slugの代わりにfilenameでテンプレートを指定
    operations:
      create: true    # 新規作成は許可（不要なら false）
      rename: false   # 名前の変更を禁止
      delete: false   # 削除を禁止
    fields:
      - name: title
        label: ゼミ名
        type: string
        required: true ##必須要素指定
      - name: icon
        label: ゼミアイコン
        type: image
      - name: teacher
        label: 担当教員名
        type: string
      - name: image
        label: ゼミ画像
        type: image
      - name: description
        label: 一言概要
        type: string
      - name: body
        label: 詳細内容
        type: rich-text
      - name: sections
        label: セクション一覧
        type: block
        list: true          # ← ★【修正】blockのすぐ下に移動
        blockKey: type      # ← ★【修正】blockを複数扱うために必須の設定です
        blocks:
          - name: text_block
            label: 見出しと段落
            # list: true    # ← ★【修正】ここからは削除します
            fields:
              - name: heading
                type: string
                label: 見出し (H2)
              - name: body
                type: text
                label: 本文 (P)
          - name: image_text_block
            label: 画像付きテキスト
            fields:
              - name: image
                type: image
                label: 画像
              - name: caption
                type: string
                label: キャプション
