media:
  input: public/images/seminars
  output: /images/seminars

content:
  - name: seminars
    label: ゼミ紹介
    type: collection
    path: content/seminars
    format: yaml-frontmatter
    filename: "{slug}.md"
    operations:
      create: true
      rename: false
      delete: false
    fields:
      - name: title
        label: ゼミ名（必須）
        type: string
        required: true
      - name: icon
        label: ゼミアイコン（任意）
        description: "svg,ico,pngのいずれかの形式でお願いします。縦横1:1の比率。"
        type: image
        required: false
      - name: teacher
        label: 担当顧問
        type: string
        required: false
      - name: image
        label: ゼミ画像（任意）
        type: image
        required: false
      - name: description
        label: 一言概要（必須）
        type: string
        required: true
      - name: body
        label: 詳細内容（必須）
        type: rich-text
        required: true
      - name: sections
        label: セクション一覧（任意）
        description: "自由にセクションを増やしていただけます。"
        type: block
        list: true
        blockKey: type
        required: false
        blocks:
          - name: text_block
            label: 見出しと段落
            fields:
              - name: heading
                type: string
                label: 見出し (H2)
              - name: body
                type: text
                label: 本文 (P)
          - name: image_text_block
            label: 画像付きテキスト
            fields:
              - name: image
                type: image
                label: 画像
              - name: caption
                type: string
                label: キャプション
